// fe/src/reactDemo/ProjectDetail.jsx
import {useEffect, useRef, useState} from 'react'
import {useParams} from 'react-router'
import {message} from 'antd'
import SearchMediaModal from './SearchMediaModal'
import {request} from '../utils'
import ProduceVideoModal from './ProduceVideoModal'
import {createEditor} from '../common/editorUtil'


const myLocale = 'zh-CN';
function ProjectDetail() {
  const [showSearchMediaModal, setShowSearchMediaModal] = useState(false)
  const [showProduceVideoModal, setShowProduceVideoModal] = useState(false)
  const containerRef = useRef();
  const searchMediaRef = useRef({})
  const produceVideoRef = useRef({})
  const params = useParams()
  const {projectId} = params
  useEffect(() => {
    if (!containerRef.current) {
      return
    }
    const {init, destroy} = createEditor({
      container: containerRef.current,
      locale: myLocale,
      // mode:'template',
      projectId,
      message,
      onSearchMedia: () => {
        return new Promise((resolve, reject) => {
          // 调用方需要自己实现展示媒资、选择媒资添加的界面
          // 关于展示媒资，请参考：https://help.aliyun.com/document_detail/197964.html
          searchMediaRef.current = {
            resolve,
            reject
          }
          setShowSearchMediaModal(true)
        })
      },

      onProduceEditingProjectVideo: ({coverUrl, duration = 0, aspectRatio, timeline, recommend}) => {
        return new Promise((resolve, reject) => {
          produceVideoRef.current = {
            aspectRatio,
            recommend,
            timeline,
            resolve,
            reject
          }
          setShowProduceVideoModal(true)
        })
      },

    })
    init();
    return () => {
      destroy()
    }
  }, [projectId, containerRef, searchMediaRef])

  return (
    <div>
      <div ref={containerRef} style={{height: '100vh'}} />
      {showSearchMediaModal && (
        <SearchMediaModal
          onSubmit={(info) => {
            setShowSearchMediaModal(false)
            searchMediaRef.current.resolve(info)
          }}
          onClose={() => {
            setShowSearchMediaModal(false)
            searchMediaRef.current.reject()
          }}
          projectId={projectId}
        />
      )}
      {showProduceVideoModal && (
        <ProduceVideoModal
          aspectRatio={produceVideoRef.current.aspectRatio}
          recommend={produceVideoRef.current.recommend}
          onSubmit={async ({fileName, format, bitrate, resolution, ossBucket}) => { // 假设提交合成任务的界面让你获得了这些数据
            // 先根据 fileName 和 format 拼接出存储的 mediaURL
            let mediaURL ;
            let OutputMediaTarget = 'oss-object';
            let  StorageLocation;
            let FileName;
            if(ossBucket.indexOf('vod://') === 0){
              OutputMediaTarget = 'vod-media';
              StorageLocation = ossBucket.replace('vod://','')
              FileName = `${ fileName }.${ format }`;
            } else{
              mediaURL  = `${ ossBucket }${ fileName }.${ format }`;
            }
            const [width, height] = resolution;
            try {
              await request('SubmitMediaProducingJob', { // https://help.aliyun.com/document_detail/197853.html
                OutputMediaConfig: JSON.stringify({
                  mediaURL,
                  bitrate,
                  width,
                  height,
                  StorageLocation,
                  FileName
                }),
                OutputMediaTarget ,
                ProjectId: projectId,
                Timeline: JSON.stringify(produceVideoRef.current.timeline)
              })
              message.success('生成视频成功')
              setShowProduceVideoModal(false)
              produceVideoRef.current.resolve();
            } catch (ex) {
              message.success('生成视频失败');
              setShowProduceVideoModal(false);
              produceVideoRef.current.resolve();
            }
          }}
          onClose={() => {
            setShowProduceVideoModal(false)
            produceVideoRef.current.reject()
          }}
        />
      )}
    </div>
  )
}

export default ProjectDetail

// fe/src/vueDemo/ProjectDetail.vue
<template>
  <div id="app" ref="containerRef" style="height: 100vh"></div>
  <template v-if="searchMediaShowRef">
    <SearchMediaModal
      :project-id="projectIdRef"
      @submit="onSearchMediaSubmit"
      @close="onSearchMediaClose"
    />
  </template>
  <template v-if="produceVideoShowRef">
    <ProduceVideoModal
      :aspect-ratio="produceVideoRef.aspectRatio"
      :recommend="produceVideoRef.recommend"
      @submit="onProduceVideoSubmit"
      @close="onProduceVideoClose"
    />
  </template>
  <contextHolder />
</template>
<script lang="ts" setup>
import { onMounted, onUnmounted, ref, watch } from "vue";
import { useRoute } from "vue-router";
import { createEditor } from "../common/editorUtil";
import { request } from "../utils";
import SearchMediaModal from "./SearchMediaModal.vue";
import ProduceVideoModal from "./ProduceVideoModal.vue";
import { message } from "ant-design-vue";

const [messageApi, contextHolder] = message.useMessage();

const containerRef = ref<HTMLDivElement | null>(null);
const editorRef = ref<{ destroy: () => void } | null>(null);
const route = useRoute();
const projectIdRef = ref(route.params.projectId as string);
const searchMediaRef = ref({ resolve: (v: any) => {} });
const searchMediaShowRef = ref(false);
const produceVideoRef = ref<{
  timeline: any;
  aspectRatio?: any;
  recommend?: any;
  resolve: () => void;
}>({ resolve: () => {}, timeline: {} });
const produceVideoShowRef = ref(false);
const myLocale = "zh-CN";

watch(
  () => route.params.projectId,
  (value) => {
    if (typeof value === "string") {
      projectIdRef.value = value;
    } else {
      projectIdRef.value = value[0];
    }
  }
);
const onSearchMediaSubmit = (res) => {
  searchMediaRef.value.resolve(res);
  searchMediaShowRef.value = false;
};
const onSearchMediaClose = () => {
  searchMediaShowRef.value = false;
};

const onProduceVideoSubmit = async ({
  fileName,
  format,
  bitrate,
  resolution,
  ossBucket,
}) => {
  // 先根据 fileName 和 format 拼接出存储的 mediaURL

  let mediaURL;
  let OutputMediaTarget = "oss-object";
  let StorageLocation;
  let FileName;
  if (ossBucket.indexOf("vod://") === 0) {
    OutputMediaTarget = "vod-media";
    StorageLocation = ossBucket.replace("vod://", "");
    FileName = `${fileName}.${format}`;
  } else {
    mediaURL = `${ossBucket}${fileName}.${format}`;
  }

  const [width, height] = resolution;
  try {
    await request("SubmitMediaProducingJob", {
      // https://help.aliyun.com/document_detail/197853.html
      OutputMediaConfig: JSON.stringify({
        mediaURL,
        bitrate,
        width,
        height,
        StorageLocation,
        FileName,
      }),
      OutputMediaTarget,
      ProjectId: projectIdRef.value,
      Timeline: JSON.stringify(produceVideoRef.value.timeline),
    });
    message.success("生成视频成功");
    produceVideoShowRef.value = false;
    produceVideoRef.value.resolve();
  } catch (ex) {
    message.success("生成视频失败");
    produceVideoShowRef.value = false;
    produceVideoRef.value.resolve();
  }
  produceVideoRef.value.resolve();
  produceVideoShowRef.value = false;
};
const onProduceVideoClose = () => {
  produceVideoShowRef.value = false;
};
onMounted(() => {
  if (!containerRef.value || !projectIdRef.value) {
    return;
  }
  const editor = createEditor({
    container: containerRef.value,
    projectId: projectIdRef.value,
    locale: myLocale,
    mode: undefined,
    onSearchMedia: async () => {
      searchMediaShowRef.value = true;
      return new Promise<any>((resolve) => {
        searchMediaRef.value = { resolve: resolve };
      });
    },
    onProduceEditingProjectVideo: async ({
      coverUrl,
      duration = 0,
      aspectRatio,
      timeline,
      recommend,
    }) => {
      produceVideoShowRef.value = true;
      return new Promise<void>((resolve) => {
        produceVideoRef.value = {
          resolve: resolve,
          timeline,
          aspectRatio,
          recommend,
        };
      });
    },
    message:messageApi,
  });
  editor.init();
  editorRef.value = editor;
});

onUnmounted(() => {
  if (editorRef.value) {
    editorRef.value.destroy();
  }
});
</script>
