// fe/src/vueDemo/ProjectList.vue
<template>
  <a-card
  title='工程列表'
    style="width: 80%;margin: 0 auto;"
  >
   <template #extra >
    <div>
     <a-button type="primary"  @click="onModalOpen" >
      创建工程
     </a-button>
     </div>
   </template>
    <a-list item-layout="horizontal" :data-source="data.list">
    <template #renderItem="{ item }">
      <a-list-item>
        <a-list-item-meta>
         <template  #title >
          <router-link  :to="`detail/${item.ProjectId}`" > {{ item.Title }}</router-link>
         </template>
        </a-list-item-meta>
        <a-button :style="{marginLeft: '10px'}" @click="router.push(`/detail/${ item.ProjectId }`)" >编辑</a-button>
        <a-button :style="{marginLeft: '10px'}" @click="router.push(`/player/${ item.ProjectId }`)" >预览</a-button>
      </a-list-item>
    </template>
  </a-list>
  <a-pagination v-model:current="current" :total="data.total"   />
  </a-card>
 <a-modal v-model:open="openModal" title="创建剪辑工程" :confirmLoading="okLoading" @ok="onCreateProject" @cancel="onModalClose" >
  <a-form
          v-model="fromState"

          >
            <a-form-Item name='title' label='工程名称'  >
              <a-input v-model:value="fromState.title" />
            </a-form-Item>
          </a-form>
 </a-modal>

</template>

<script lang="ts" setup >
import {request} from '../utils';
import { onMounted ,reactive,ref, watch} from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();

const data = reactive({
  list:[],
  total:0
});

const fromState = reactive({
   title:''
});

const current = ref(1);
const okLoading = ref(false);
const openModal = ref(false);

const fetchList = async ({pageNo,pageSize})=>{
  request('SearchEditingProject', {
      TemplateType: 'None',
      PageSize: pageSize,
      PageNo: pageNo
    }).then(res => {
      if (res.status === 200) {
        data.list =res.data.ProjectList;
        data.total = res.data.TotalCount;
      }
    })
}


const onModalOpen = ()=>{
  openModal.value = true;
}

const onModalClose = ()=>{
  openModal.value = false;
}

const onCreateProject = ( )=>{
  console.log('>>>>',fromState)
  okLoading.value = true;
  request('CreateEditingProject', {
      Title: fromState.title
    }).then(() => {
      okLoading.value = false;
      onModalClose();
      fetchList({pageNo: current.value,pageSize:10});
    })
}

onMounted(()=>{
  fetchList({pageNo:1,pageSize:10})
});

 watch(current,()=>{
  fetchList({pageNo:current.value,pageSize:10})
 });

</script>

// fe/src/reactDemo/ProjectList.jsx
import {useEffect, useState} from 'react'
import {Link} from 'react-router-dom'
import {Button, Card, Form, Input, Modal, List, Pagination} from 'antd'
import {request} from '../utils'

const layout = {
  labelCol: {span: 4},
  wrapperCol: {span: 20}
}
const PageSize = 10;
function ProjectList() {
  const [list, setList] = useState([])
  const [showModal, setShowModal] = useState(false)
  const [confirmLoading, setConfirmLoading] = useState(false)
  const [version, setVersion] = useState(1)
  const [total, setTotal] = useState(0)
  const [pageNo, setPageNo] = useState(1)
  const [form] = Form.useForm()

  useEffect(() => {
    request('SearchEditingProject', {
      TemplateType: 'None',
      PageSize: PageSize,
      PageNo: pageNo
    }).then(res => {
      if (res.status === 200) {
        setList(res.data.ProjectList)
        setTotal(res.data.TotalCount)
      }
    })
  }, [version, pageNo])

  const handleSubmit = (values) => {
    setConfirmLoading(true)
    request('CreateEditingProject', {
      Title: values.title
    }).then(() => {
      setConfirmLoading(false)
      setShowModal(false)
      setVersion(v => v + 1)
    })
  }

  return (<div>

    <Card
      extra={
        <div>
          <Button type='primary' onClick={() => setShowModal(true)}>创建工程</Button>
          <Button style={{marginLeft: '10px'}} onClick={() => {
            window.location.href = '/player.html'
          }} >预览播放器</Button>
        </div>
      }
      title='工程列表'
      style={{width: '80%', margin: '50px auto'}}
    >
      <div>

        <List
          dataSource={list}
          renderItem={(item, index) => {
            return <List.Item  >
              <Link style={{display: 'block'}} to={`/detail/${ item.ProjectId }`}>
                {index + 1}. {item.Title}
              </Link>
              <div>
                <Link to={`/detail/${ item.ProjectId }`} target='_blank' >
                  <Button style={{marginRight: '10px'}} >编辑</Button>
                </Link>
                <Button style={{marginLeft: '10px'}} onClick={() => {
                  window.location.href = `/player.html#/projectTimeline/${ item.ProjectId }`
                }} >预览</Button>
              </div>
            </List.Item>
          }}
        />
        <Pagination current={pageNo} total={total} pageSize={PageSize} pageSizeOptions={[10]} onChange={(n) => {
          setPageNo(n);
        }} />
      </div>
      {showModal && (
        <Modal
          open
          title='创建剪辑工程'
          okText='提交'
          cancelText='取消'
          onOk={() => form.submit()}
          onCancel={() => setShowModal(false)}
          confirmLoading={confirmLoading}
        >
          <Form
            {...layout}
            form={form}
            onFinish={handleSubmit}
          >
            <Form.Item name='title' label='工程名称' rules={[{required: true}]}>
              <Input />
            </Form.Item>
          </Form>
        </Modal>
      )}
    </Card>
  </div>
  )
}

export default ProjectList
